add channel notification on member join
Lymdun/HidamariBot pull request #3
Opened 2024-10-22 01:31 UTC by LaNotice

Envoi une notification dans le channel d'entrée dès qu'un membre rejoint le serveur :3

2024-10-22 01:39 UTC, Zerotistic requested changes

2024-10-22 01:39 UTC, Zerotistic commented on Services/MemberJoinService.cs
> +                .WithContent($"{Mention.User(newMember.Id)} Bienvenue dans l'antre de lymdzoune");
Il faut rediriger le nouveau membre vers le modèle de présentation afin qu'il puisse passer le rideau de fer 🤓

2024-10-25 21:37 UTC, Lymdun commented on Services/MemberJoinService.cs
> +                .WithContent($"{Mention.User(newMember.Id)} Bienvenue dans l'antre de lymdzoune");
Ne pas utiliser **var** lorsque le new donne explicitement le type n'est pas autorisé.

2024-10-25 22:06 UTC, LaNotice commented on Services/MemberJoinService.cs
> +                .WithContent($"{Mention.User(newMember.Id)} Bienvenue dans l'antre de lymdzoune");
normalement j'ai résolu ça dans le dernier commit

2024-10-26 14:51 UTC, Lymdun requested changes

2024-10-26 14:51 UTC, Lymdun commented on Services/MemberJoinService.cs
> +                await using (FileStream fs = new FileStream(IMAGE_PATH, FileMode.Open, FileAccess.Read)) {
WHY

2024-10-26 14:51 UTC, Lymdun commented on Services/MemberJoinService.cs
> +    const string QUESTIONNAIRE = "https://discord.com/channels/450280270654865439/1203052960712622110/1203439457248743425";
Rename it to 'QUESTIONNAIRE_MESSAGE_PATH'

2024-10-26 14:51 UTC, Lymdun commented on Services/MemberLeaveService.cs
> +                await using (FileStream fs = new FileStream(IMAGE_PATH, FileMode.Open, FileAccess.Read)) {
NO

2024-10-26 14:54 UTC, Lymdun commented on Services/MemberJoinService.cs
>              LocalMessage message = new LocalMessage()
Should be var

2024-10-26 15:16 UTC, merged